# Generated by Django 3.1.5 on 2023-07-23 17:06

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20230723_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='yaziModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='yaziResimleri')),
                ('baslik', models.CharField(max_length=50)),
                ('icerik', models.TextField()),
                ('olustulumaTarihi', models.DateTimeField(auto_now_add=True)),
                ('duzenlenmeTarihi', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='baslik', unique=True)),
                ('kategoriler', models.ManyToManyField(related_name='yazi', to='blog.kategoriModel')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yazilar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'yazi',
                'verbose_name_plural': 'yazilar',
                'db_table': 'yazi',
            },
        ),
    ]
