# Generated by Django 3.1.5 on 2023-07-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_yazimodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yazimodel',
            old_name='olustulumaTarihi',
            new_name='olusturulmaTarihi',
        ),
    ]
